### ISSUE TITLE
Class "Zend\Mail\Header\HeaderValue" not found

### ISSUE THREAD

**Issue by roma84** [swissup/module-email#30]
Magento 2.4.6-p4 php 8.1

https://github.com/swissup/module-email/blob/master/Mail/Message/Convertor.php#L46

```
Error: Class "Zend\Mail\Header\HeaderValue" not found in /home/usams/public_html/vendor/swissup/module-email/Mail/Message/Convertor.php:46
Stack trace:
#0 [internal function]: Swissup\Email\Mail\Message\Convertor->Swissup\Email\Mail\Message\{closure}()
#1 /home/usams/public_html/vendor/swissup/module-email/Mail/Message/Convertor.php(50): array_map()
#2 /home/usams/public_html/vendor/swissup/module-email/Mail/Transport.php(109): Swissup\Email\Mail\Message\Convertor->fromMessage()
#3 /home/usams/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Swissup\Email\Mail\Transport->sendMessage()
#4 /home/usams/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Swissup\Email\Mail\Transport\Interceptor->___callParent()
#5 /home/usams/public_html/vendor/swissup/module-gdpr/Plugin/MailTransport.php(49):
Swissup\Email\Mail\Transport\Interceptor->Magento\Framework\Interception\{closure}()
#6 /home/usams/public_html/vendor/magento/framework/Interception/Interceptor.php(135): Swissup\Gdpr\Plugin\MailTransport->aroundSendMessage()
#7 /home/usams/public_html/vendor/magento/module-email/Model/Mail/TransportInterfacePlugin.php(48):
Swissup\Email\Mail\Transport\Interceptor->Magento\Framework\Interception\{closure}()
#8 /home/usams/public_html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Email\Model\Mail\TransportInterfacePlugin->aroundSendMessage()
#9 /home/usams/public_html/vendor/magento/framework/Interception/Interceptor.php(153):
Swissup\Email\Mail\Transport\Interceptor->Magento\Framework\Interception\{closure}()
#10 /home/usams/public_html/generated/code/Swissup/Email/Mail/Transport/Interceptor.php(23): Swissup\Email\Mail\Transport\Interceptor->___callPlugins()
#11 /home/usams/public_html/vendor/swissup/module-email/Controller/Adminhtml/Email/Service/Check.php(125): Swissup\Email\Mail\Transport\Interceptor->sendMessage()
#12 /home/usams/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Swissup\Email\Controller\Adminhtml\Email\Service\Check->execute()
#13 /home/usams/public_html/vendor/magento/framework/Interception/Interceptor.php(138):
Swissup\Email\Controller\Adminhtml\Email\Service\Check\Interceptor->___callParent()
#14 /home/usams/public_html/vendor/magento/framework/Interception/Interceptor.php(153):
Swissup\Email\Controller\Adminhtml\Email\Service\Check\Interceptor->Magento\Framework\Interception\{closure}()
#15 /home/usams/public_html/generated/code/Swissup/Email/Controller/Adminhtml/Email/Service/Check/Interceptor.php(23):
Swissup\Email\Controller\Adminhtml\Email\Service\Check\Interceptor->___callPlugins()
#16 /home/usams/public_html/vendor/magento/framework/App/Action/Action.php(111): Swissup\Email\Controller\Adminhtml\Email\Service\Check\Interceptor->execute()
#17 /home/usams/public_html/vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch()
#18 /home/usams/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch()
#19 /home/usams/public_html/vendor/magento/framework/Interception/Interceptor.php(138):
Swissup\Email\Controller\Adminhtml\Email\Service\Check\Interceptor->___callParent()
#20 /home/usams/public_html/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(145):
Swissup\Email\Controller\Adminhtml\Email\Service\Check\Interceptor->Magento\Framework\Interception\{closure}()
#21 /home/usams/public_html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch()
#22 /home/usams/public_html/vendor/magento/framework/Interception/Interceptor.php(153):
Swissup\Email\Controller\Adminhtml\Email\Service\Check\Interceptor->Magento\Framework\Interception\{closure}()
#23 /home/usams/public_html/generated/code/Swissup/Email/Controller/Adminhtml/Email/Service/Check/Interceptor.php(32):
Swissup\Email\Controller\Adminhtml\Email\Service\Check\Interceptor->___callPlugins()
#24 /home/usams/public_html/vendor/magento/framework/App/FrontController.php(245): Swissup\Email\Controller\Adminhtml\Email\Service\Check\Interceptor->dispatch()
#25 /home/usams/public_html/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#26 /home/usams/public_html/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#27 /home/usams/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#28 /home/usams/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#29 /home/usams/public_html/vendor/magento/framework/Interception/Interceptor.php(153):
Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#30 /home/usams/public_html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23):
Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#31 /home/usams/public_html/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#32 /home/usams/public_html/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#33 /home/usams/public_html/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#34 {main}
```

**Comment by 0m3r** [comment]
https://github.com/swissup/module-email/commit/00df57eeaf246c9d6e42a119c10601ef898258c0

https://github.com/swissup/email/releases/0.5.11
